"""
Django settings for sandbox project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import django.contrib.auth
django.contrib.auth.LOGIN_URL = '/'


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

SITE_ID = 1

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%$y2+n2afk7k^d+*mvkd9ei$bsylv=*l@)txrty1$+4^)yi)2c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'filer',
    'easy_thumbnails',
    'djangocms_column',
    'djangocms_link',
    'cmsplugin_filer_file',
    'cmsplugin_filer_folder',
    'cmsplugin_filer_image',
    'cmsplugin_filer_utils',
    'djangocms_snippet',
    'djangocms_googlemap',
    'djangocms_video',
    'aldryn_style',
    'mptt',
    'aldryn_bootstrap3',
    # custom shiz
    #'simpleplugin',
    'sandbox',
    'signup'
]

MIDDLEWARE_CLASSES = (
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware'
)

ROOT_URLCONF = 'sandbox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'sandbox', 'templates'),],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'django.template.loaders.eggs.Loader'
            ],
        },
    },
]

WSGI_APPLICATION = 'sandbox.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    "default": {
        # Add "postgresql_psycopg2", "mysql", "sqlite3" or "oracle".
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        # DB name or path to database file if using sqlite3.
        "NAME": os.getenv('POSTGRES_DB', 'djcms'),
        # Not used with sqlite3.
        "USER": os.getenv('POSTGRES_USER', 'postgres'),
        # Not used with sqlite3.
        "PASSWORD": os.getenv('POSTGRES_PASSWORD', 'postgres'),
        # Set to empty string for localhost. Not used with sqlite3.
        "HOST": os.getenv('POSTGRES_HOST', 'postgres'),
        # Set to empty string for default. Not used with sqlite3.
        "PORT": os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

#CMS settings

CMS_TEMPLATES = (
    ## Customize this
    ('fullwidth.html', 'Fullwidth'),
    ('sidebar_left.html', 'Sidebar Left'),
    ('sidebar_right.html', 'Sidebar Right'),
    ('home.html', 'home'),
    ('index.html', 'index'),
    ('services.html', 'services'),
    ('base2.html', 'base2'),
    ('supportDashboard.html', 'supportAccount'),
    ('stuffDashboard.html', 'stuffAccount'),
    ('userDashboard.html', 'userAccount')
)

LANGUAGES = [
        ('en-us', 'English'),
    ]

CMS_PERMISSION = True


MIGRATION_MODULES = {
    
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

CKEDITOR_SETTINGS = {
# 'language': '{{ language }}',
 # 'toolbar': 'CMS',
 # 'skin': 'moono',
 # 'toolbar_CMS': [
 #  ['Undo', 'Redo'],
 #  ['cmsplugins', '-', 'ShowBlocks'],
 #  ['Format', 'Styles'],
 #  ['TextColor', 'BGColor', '-', 'PasteText', 'PasteFromWord'],
 #  ['Maximize', ''],
 #  '/',
 #  ['Bold', 'Italic', 'Underline', '-', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
 #  ['JustifyLeft', 'JustifyCenter', 'JustifyRight'],
 #  ['Link', 'Unlink', 'Anchor'],
 #  ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Table'],
 #  ['Source']
 # ],

 # See: https://github.com/yakupadakli/django_blog/blob/master/ckeditor/ckeditor/styles.js
 # for default style definitions.
 'stylesSet': [
  {
   'name': 'Page Header H1',
   'element': 'h1',
   'attributes': {
    'class': 'page-header',
   }
  },
  {
   'name': 'Page Header H2',
   'element': 'h2',
   'attributes': {
    'class': 'page-header',
   }
  },
  {
   'name': 'Page Header H3',
   'element': 'h3',
   'attributes': {
    'class': 'page-header',
   }
  },
  {
   'name': 'Code',
   'element': 'code',
  },
  {
   'name': 'Code Block',
   'element': 'pre',
   'attributes': {
    'class': 'code',
   }
  },
 ],
}
